export const achievements: AchievementType[] = [
  {
    id: '0',
    title: 'First Run',
    description: 'You ran for the first time!',
    icon: '🏃‍♂️',
    completed: false,
  },
  {
    id: '1',
    title: '10 Runs',
    description: 'You ran 10 times!',
    icon: '🏃‍♂️',
    completed: false,
  },
  {
    id: '2',
    title: '50 Runs',
    description: 'You ran 50 times!',
    icon: '🏃‍♂️',
    completed: false,
  },
  {
    id: '3',
    title: '100 Runs',
    description: 'You ran 100 times!',
    icon: '🏃‍♂️',
    completed: false,
  },
  {
    id: '4',
    title: '500 Runs',
    description: 'You ran 500 times!',
    icon: '🏃‍♂️',
    completed: false,
  },
  {
    id: '5',
    title: '1000 Runs',
    description: 'You ran 1000 times!',
    icon: '🏃‍♂️',
    completed: false,
  },
  {
    id: '6',
    title: '5000 Runs',
    description: 'You ran 5000 times!',
    icon: '🏃‍♂️',
    completed: false,
  },
  {
    id: '7',
    title: '10000 Runs',
    description: 'You ran 10000 times!',
    icon: '🏃‍♂️',
    completed: false,
  },
  {
    id: '8',
    title: '50000 Runs',
    description: 'You ran 50000 times!',
    icon: '🏃‍♂️',
    completed: false,
  },
  {
    id: '9',
    title: '100000 Runs',
    description: 'You ran 100000 times!',
    icon: '🏃‍♂️',
    completed: false,
  },
  {
    id: '10',
    title: '500000 Runs',
    description: 'You ran 500000 times!',
    icon: '🏃‍♂️',
    completed: false,
  },
];
